---
- name: Ensure Docker-related Python packages are present
  pip:
    name:
      - docker
      - docker-compose

- name: Ensure the config directory is present
  file:
    path: /opt/mozilla_syncserver
    state: directory
    mode: 0755
    owner: 1001
    group: 1001

- name: Define the default docker container volumes
  set_fact:
    _mozilla_syncserver_docker_volumes:
      - "/opt/mozilla_syncserver:/data"

- name: Append any additional volume mounts
  set_fact:
    _mozilla_syncserver_docker_volumes: "{{ _mozilla_syncserver_docker_volumes }} + {{ mozilla_syncserver_additional_volumes }}"

- name: Ensure the docker-compose template directory exists
  file:
    state: directory
    path: "/opt/ansible-docker-compose/mozilla-syncserver"

- name: Ensure this service's docker-compose template is present
  template:
    src: docker-compose.yml.j2
    dest: /opt/ansible-docker-compose/mozilla-syncserver/docker-compose.yml

- name: Ensure the service container(s) is/are started
  docker_compose:
    project_src: /opt/ansible-docker-compose/mozilla-syncserver
    pull: yes
