---
- name: restart mozilla-syncserver
  docker_container:
    name: mozilla-syncserver
    image: "mozilla/syncserver:{{ mozilla_syncserver_docker_version }}"
    state: started
    restart_policy: always
    timeout: 300
    exposed_ports:
      - "{{ mozilla_syncserver_port }}" # sync endpoint
    volumes: "{{ _mozilla_syncserver_docker_volumes }}"
    env: "{{ mozilla_syncserver_environment_variables }}"
    restart: true
